Update dsp.py
If during start or switching of a profile the secondary chain is not available, it is initialized.
This should prevent the following error (NIL pointer exception):

AttributeError: 'NoneType' object has no attribute 'setReader'
2026-02-14 17:50:44,563 - owrx.websocket - ERROR - Exception in websocket handler handleTextMessage()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/owrx/websocket.py", line 230, in read_loop
    self.messageHandler.handleTextMessage(self, message)
  File "/usr/lib/python3/dist-packages/owrx/connection.py", line 329, in handleTextMessage
    dsp.start()
  File "/usr/lib/python3/dist-packages/owrx/dsp.py", line 840, in start
    self.chain.setReader(self.sdrSource.getBuffer().getReader())
    ^^^^^^^^^^^^^^^^^^^^